version: "3.8"

services:
  main:
    build: .
    environment:
      - MYSQL_ENABLED=True
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_USER=test
      - MYSQL_PASSWORD=1234567
      - MYSQL_DB=test
    networks:
      internal_network:
    ports:
      - 6881:6881/tcp
      - 6881:6881/udp
    volumes:
      - ./tmp/:/tmp/
      - ./conf:/opt/torsniff/conf:ro
      - ./log:/opt/torsniff/log:delegated
    depends_on:
      - mysql

#  redis:
#    image: redis:alpine
#    command: redis-server --save 60 1
#    volumes:
#      - ./redis:/data
#    networks:
#      internal_network:
#        ipv4_address: 172.25.0.2

  mysql:
    image: mariadb:10.5
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE:-test}
      - MYSQL_USER=${MYSQL_USER:-test}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-1234567}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-1234567}
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      internal_network:
        ipv4_address: 172.25.0.3

networks:
  internal_network:
    driver: bridge
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 172.25.0.0/16


