version: "3.8"

services:
  main:
    build: .
    ports:
      - 6881:6881/tcp
      - 6881:6881/udp
    volumes:
      - ./conf:/opt/torsniff/conf:ro
      - ./log:/opt/torsniff/log:delegated
    depends_on:
      - redis

  redis:
    image: redis:alpine
    command: redis-server --save 60 1
    volumes:
      - ./redis:/data

  mysql:
    image: mariadb:10.5
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE:-test}
      - MYSQL_USER=${MYSQL_USER:-test}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-1234567}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-1234567}
    volumes:
      - ./mysql:/var/lib/mysql

